version : "4.26.1"

services:
  web:
    build: .
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    image: application:django
    container_name: app_container
    command: python manage.py runserver 0.0.0.0:8000